import {StyleSheet, Dimensions} from 'react-native';

const {width} = Dimensions.get('window');
const cardWidth = width * 0.7;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  scrollContent: {
    padding: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 24,
    borderRadius: 8,
    elevation: 2,
  },
  logo: {
    width: 120,
    height: 40,
  },
  menuButton: {
    padding: 8,
  },
  menuLine: {
    width: 24,
    height: 2,
    backgroundColor: '#333333',
    marginVertical: 2,
    borderRadius: 1,
  },
  rupfixSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  rupfixLogoContainer: {
    width: 48,
    height: 48,
    marginRight: 12,
    backgroundColor: '#F8F9FA',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 1,
  },
  rupfixLogo: {
    width: '80%',
    height: '80%',
  },
  rupfixText: {
    fontSize: 28,
    fontWeight: 'bold',
  },
  rupText: {
    color: '#0066FF',
  },
  fixText: {
    color: '#003399',
  },
  infoContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
    elevation: 2,
  },
  infoSection: {
    marginBottom: 16,
  },
  badge: {
    backgroundColor: '#462556',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  infoText: {
    color: '#0066FF',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 4,
  },
  taxationContainer: {
    marginVertical: 8,
  },
  taxationWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#462556',
    borderRadius: 30,
    padding: 16,
    elevation: 2,
  },
  taxationLogoSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    padding: 12,
    marginRight: 16,
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  taxationLogo: {
    width: '90%',
    height: '90%',
  },
  taxationTextContainer: {
    flex: 1,
  },
  taxationText: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: 'bold',
    lineHeight: 34,
  },
  taxationPanelText: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: 'bold',
    lineHeight: 34,
  },
  walletsContainer: {
    marginVertical: 16,
    gap: 12,
  },
  walletContainer: {
    marginBottom: 12,
  },
  walletCard: {
    borderRadius: 16,
    padding: 16,
    minHeight: 120,
  },
  walletHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  walletTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  walletAmount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  addButton: {
    backgroundColor: '#e88e73',
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  withdrawButton: {
    alignSelf: 'flex-start',
  },
  withdrawButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  serviceContainer: {
    marginBottom: 12,
  },
  serviceCard: {
    borderRadius: 16,
    padding: 16,
    minHeight: 120,
  },
  serviceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  serviceTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  serviceSubtitle: {
    fontSize: 14,
    color: '#FFFFFF',
    marginBottom: 12,
    opacity: 0.9,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 16,
  },
  serviceButton: {
    alignSelf: 'flex-start',
  },
  serviceButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  searchContainer: {
    marginBottom: 12,
  },
  searchCard: {
    borderRadius: 16,
    padding: 20,
    minHeight: 140,
  },
  searchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 4,
  },
  searchIcon: {
    opacity: 0.9,
  },
  searchTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  searchSubtitle: {
    fontSize: 14,
    color: '#FFFFFF',
    opacity: 0.9,
    marginBottom: 16,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 25,
    paddingLeft: 16,
    paddingRight: 4,
    paddingVertical: 4,
    marginTop: 8,
  },
  searchInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 16,
    paddingVertical: 8,
  },
  searchButton: {
    backgroundColor: '#e94f37',
    padding: 10,
    borderRadius: 20,
    marginLeft: 8,
  },
  searchButtonText: {
    fontSize: 20,
  },
  loanbazziContainer: {
    marginVertical: 16,
  },
  loanbazziWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#462556',
    borderRadius: 50,
    padding: 16,
    elevation: 2,
  },
  loanbazziLogoSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    padding: 12,
    marginRight: 16,
    flex: 1,
    maxWidth: '75%',
  },
  loanbazziLogo: {
    width: '100%',
    height: 28,
  },
  loanbazziPanelText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  loanCardsContainer: {
    marginVertical: 16,
    gap: 16,
    borderRadius: 16,
    padding: 16,
    // margin: 12,
    minHeight: 120,
  },
  loanCard: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  cardContent: {
    padding: 24,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  cardContainer: {
    padding: 10,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  amountText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 12,
    
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF4500',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignSelf: 'flex-start',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
  insurancePanelContainer: {
    marginVertical: 16,
  },
  insurancePanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#462556',
    borderRadius: 30,
    padding: 16,
    marginBottom: 16,
  },
  tulyarthLogoContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 8,
    marginRight: 12,
    width: 120,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tulyarthLogo: {
    width: '100%',
    height: '100%',
  },
  insuranceTextContainer: {
    flexDirection: 'column',
  },
  insuranceText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 28,
  },
  panelText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 28,
  },
  insuranceCardsContainer: {
    paddingVertical: 8,
    gap: 16,
  },
  insuranceCard: {
    width: cardWidth,
    borderRadius: 16,
    padding: 24,
    elevation: 2,
  },
  insuranceHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  insuranceTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  insuranceSubtitle: {
    fontSize: 16,
    color: '#FFFFFF',
    marginBottom: 20,
    opacity: 0.9,
  },
  insuranceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF4500',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignSelf: 'flex-start',
  },
  insuranceButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
  digiwebPanelContainer: {
    marginVertical: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
  },
  tulyaDigiwebContainer: {
    marginBottom: 0,
  },
  tulyaDigiwebWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#462556',
    borderRadius: 30,
    padding: 16,
    marginBottom: 16,
  },
  tulyaDigiwebLogoSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 8,
    marginRight: 12,
    width: 120,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tulyaDigiwebLogo: {
    width: '100%',
    height: '100%',
  },
  tulyaText: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
    lineHeight: 24,
  },
  dotTh: {
    color: '#FF6700',
    fontWeight: 'bold',
  },
  digiwebText: {
    color: '#009688',
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 28,
  },
  codeIcon: {
    color: '#333',
    fontSize: 20,
  },
  panelTextBig: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    lineHeight: 34,
  },
  digiwebHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  digiwebLogoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  digiwebLogo: {
    width: 120,
    height: 40,
    backgroundColor: '#462556',
    borderRadius: 8,
    marginRight: 8,
  },
  digiwebCardsContainer: {
    gap: 16,
  },
  digiwebCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    borderRadius: 16,
    elevation: 3,
  },
  digiwebCardContent: {
    marginLeft: 16,
    flex: 1,
  },
  digiwebCardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  digiwebCardSubtitle: {
    fontSize: 16,
    color: '#FFFFFF',
    opacity: 0.9,
    marginBottom: 12,
  },
  digiwebButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF4500',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 25,
    alignSelf: 'flex-start',
  },
  digiwebButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
  p3PanelContainer: {
    marginVertical: 16,
    padding: 16,
  },
  p3Header: {
    backgroundColor: '#462556',
    borderRadius: 50,
    padding: 12,
    marginBottom: 20,
    height: 70,
    justifyContent: 'center',
  },
  p3LogoWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
  },
  p3Logo: {
    width: 120,
    height: 40,
    marginRight: 12,
    backgroundColor: '#fff',
  },
  p3Text: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  p3CardsContainer: {
    paddingVertical: 8,
    gap: 16,
  },
  p3Card: {
    width: width * 0.7,
    borderRadius: 16,
    padding: 20,
    marginRight: 16,
    elevation: 3,
  },
  p3Icon: {
    marginBottom: 12,
  },
  p3CardContent: {
    flex: 1,
  },
  p3CardTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  p3CardSubtitle: {
    fontSize: 16,
    color: '#FFFFFF',
    opacity: 0.9,
    marginBottom: 20,
  },
  p3Button: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF4500',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignSelf: 'flex-start',
  },
  p3ButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
});

export default styles;
